---
output: github_document
---

```{r message=FALSE, echo=FALSE}
library("magrittr")
library("ggplot2")
library("dplyr")
library("lubridate")

packages = c("mlr", "mlrMBO", "mlrCPO", "mlr3", "mlr3pipelines", "mlr3tuning")
ago1day = format(Sys.time() - days(1), "%Y-%m-%d")
ago5years = format(Sys.time() - years(5), "%Y-%m-%d")
data = cranlogs::cran_downloads(package = packages, from = ago5years, to = ago1day)
data$package = factor(data$package, levels = packages)
```
```{r message=FALSE, echo=FALSE}
ggplot(data, aes(x = date, y = count)) +
  geom_smooth(se = FALSE, size = 0.5, method = "loess", span = 0.2, color = "black") +
  facet_wrap(~package, scales = "free_y") +
  labs(title = "Averaged daily CRAN downloads from RStudio mirror",
    subtitle = "Data query via package 'cranlogs'.") +
  theme_minimal()
```

```{r message=FALSE, echo=FALSE}
data %>%
  mutate(dategroup = floor_date(date, "1 month")) %>% 
  group_by(dategroup, package) %>% 
  summarise(dl_m = sum(count)) %>% 
  ggplot(aes(x = dategroup, y = dl_m)) +
  geom_line() +
  facet_wrap(~package, scales = "free_y") +
  labs(title = "Monthly CRAN downloads from RStudio mirror",
    subtitle = "Data query via package 'cranlogs'.",
    y = "count", x = "date") +
  theme_minimal()
```

## Individual Plots for each package

```{r message=FALSE, echo=FALSE}
for (pkg in packages) {
  sub_data = data %>%
    filter(package == pkg, date < floor_date(Sys.time(), "1 month")) %>%
    filter(cumsum(count) != 0) %>% 
    mutate(dategroup = floor_date(date, "1 month")) %>% 
    group_by(dategroup, package) %>% 
    summarise(dl_m = sum(count))

  g = ggplot(sub_data, aes(x = dategroup, y = dl_m)) +
  geom_line() +
  labs(title = sprintf("%s: Monthly CRAN downloads from RStudio mirror", pkg),
    subtitle = "Data query via package 'cranlogs'.",
    y = "count", x = "date") +
  theme_minimal()

  print(g)
}
```


Created on 

```{r, echo=FALSE}
Sys.Date()
```

<details>
<summary>Session Info</summary>

```{r }
sessionInfo()
```

</details>


